### ISSUE TITLE
https://haystack.deepset.ai/tutorials/08_preprocessing    provides farm-haystack as latest version of haystack

### ISSUE THREAD

**Issue by Croccodoyle** [deepset-ai/haystack-tutorials#307] opened 2024-03-10 19:28 UTC
To start, let’s install the latest release of Haystack with pip:
%%bash

pip install --upgrade pip
pip install farm-haystack[colab,ocr,preprocessing,file-conversion,pdf]

This is not the latest version and when I run I get with haystack-ai I get following error.... 

ImportError: cannot import name 'fetch_archive_from_http' from 'haystack.utils'

**Comment by anakin87** [comment] 2024-06-21 15:19
Now the tutorials of 1.x (farm-haystack) and 2.x (haystack-ai) are clearly separated.
Also, the error you were reporting should be fixed.

Feel free to reopen the issue if the problem is not fixed.

**Closed by anakin87** 2024-06-21 15:19 UTC
Labels: enhancement
