### ISSUE TITLE
EvaluationResult.load() produces SyntaxError (Tutorial 5)

### ISSUE THREAD

**Issue by mkkuemmel** [deepset-ai/haystack-tutorials#121] opened 2023-02-13 10:52 UTC
**Describe the issue**
When using EvaluationResult.load(), you get a SyntaxError:

```
Traceback (most recent call last):

  File "/opt/homebrew/Caskroom/miniforge/base/envs/unipy/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3343, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-21-bc256748e1c5>", line 1, in <module>
    saved_eval_result = EvaluationResult.load("../")

  File "/opt/homebrew/Caskroom/miniforge/base/envs/unipy/lib/python3.9/site-packages/haystack/schema.py", line 1631, in load
    node_results = {file.stem: pd.read_csv(file, **read_csv_kwargs) for file in csv_files}

  File "/opt/homebrew/Caskroom/miniforge/base/envs/unipy/lib/python3.9/site-packages/haystack/schema.py", line 1631, in <dictcomp>
    node_results = {file.stem: pd.read_csv(file, **read_csv_kwargs) for file in csv_files}

  File "/opt/homebrew/Caskroom/miniforge/base/envs/unipy/lib/python3.9/site-packages/pandas/io/parsers.py", line 688, in read_csv
    return _read(filepath_or_buffer, kwds)

  File "/opt/homebrew/Caskroom/miniforge/base/envs/unipy/lib/python3.9/site-packages/pandas/io/parsers.py", line 460, in _read
    data = parser.read(nrows)

  File "/opt/homebrew/Caskroom/miniforge/base/envs/unipy/lib/python3.9/site-packages/pandas/io/parsers.py", line 1198, in read
    ret = self._engine.read(nrows)

  File "/opt/homebrew/Caskroom/miniforge/base/envs/unipy/lib/python3.9/site-packages/pandas/io/parsers.py", line 2157, in read
    data = self._reader.read(nrows)

  File "pandas/_libs/parsers.pyx", line 847, in pandas._libs.parsers.TextReader.read

  File "pandas/_libs/parsers.pyx", line 862, in pandas._libs.parsers.TextReader._read_low_memory

  File "pandas/_libs/parsers.pyx", line 941, in pandas._libs.parsers.TextReader._read_rows

  File "pandas/_libs/parsers.pyx", line 1051, in pandas._libs.parsers.TextReader._convert_column_data

  File "pandas/_libs/parsers.pyx", line 2139, in pandas._libs.parsers._apply_converter

  File "/opt/homebrew/Caskroom/miniforge/base/envs/unipy/lib/python3.9/ast.py", line 62, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')

  File "/opt/homebrew/Caskroom/miniforge/base/envs/unipy/lib/python3.9/ast.py", line 50, in parse
    return compile(source, filename, mode, flags,

  File "<unknown>", line unknown
    
    ^
SyntaxError: unexpected EOF while parsing
```

**To Reproduce**
Steps to reproduce the behavior: Run Tutorial 5

**Expected behavior**
Loading the previously saved evaluation result.

**What environment did you try to run the tutorial on?:**
 - Browser chrome
 - Haystack Version farm-haystack @ git+https://github.com/deepset-ai/haystack.git@508d9f6b3228fe2cdb2aba072057bfd0d7531c83

<img width="467" alt="image" src="https://user-images.githubusercontent.com/45412072/218439416-f3deb16e-d5ee-48b8-a807-d88327a28418.png">

**Comment by TuanaCelik** [comment] 2023-02-16 15:58
@mkkuemmel - we're trying to replicate this issue ourselves. It's the same one that's been failing in the nightlies. Just fyi..

**Comment by TuanaCelik** [comment] 2023-03-13 12:50
Hey @bilgeyucel - now that we don't have to `generate_markdowns` the review process of this will be smooth so I'm assigning to you. 
I was unable to reproduce this issue, but it's failing on the nightly builds too.
Ideally, alongside the fix, we would also update the installation to be with `farm-haystack` rather than the github installation.

**Comment by tholor** [comment] 2023-03-13 18:26
I was able to reproduce it on Colab (opening it from [here](https://haystack.deepset.ai/tutorials/05_evaluation)). Let's fix it asap as this is really a bad user experience!

**Comment by bilgeyucel** [comment] 2023-03-13 18:28
I could reproduce it as well, I am working to fix it

**Comment by bilgeyucel** [comment] 2023-03-14 16:58
I opened a PR to fix this issue. It will be a temporary fix to have a running tutorial. I'll close this issue when the issue on Haystack repository is fixed: https://github.com/deepset-ai/haystack/issues/4411

**Closed** 2023-04-13 16:18 UTC
Labels: bug
